server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: offer
      username: admin
      password: admin
      authentication-database: admin

webdriver:
  host: http://localhost:4444/wd/hub

logging:
  level:
    org.openqa.selenium: ERROR

website-to-parse:
  justjoinit:
    domain: https://justjoin.it
    div-to-offer-list: //*[@id="root"]/div[3]/div[1]/div/div[2]/div[1]/div/div
    offer:
      height: 68px
      end-of-offers-message-announcing: 'Subscribe to the job alert:'
    skill:
      class-name: css-1xm32e0