server:
  port: 8082

spring:
  mongodb:
    embedded:
      version: 4.7.0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: offer
      username: admin
      password: admin
      authentication-database: admin
  rabbitmq:
    username: ${RABBIT_USERNAME:max_user_rabbit}
    password: ${RABBIT_PASSWORD:max_password_rabbit}
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_HOST:5672}

message-broker-custom-config:
  message:
    expiration-time-ms: 600000
    retry-on-fail:
      max-duration-sec: 30
      interval-ms: 1000
  broker:
    retry-on-fail-connection:
      max-attempts: 4
      exponential-backoff-ms: 6000
      jitter-factor: 0

webdriver:
  host: http://localhost:4444/wd/hub

logging:
  level:
    org.openqa.selenium: ERROR

website-to-parse:
  justjoinit:
    domain: https://justjoin.it
    div-to-offer-list: //*[@id="root"]/div[3]/div[1]/div/div[2]/div[1]/div/div
    offer:
      height: 68px
      end-of-offers-message-announcing: 'Subscribe to the job alert:'
    skill:
      class-name: css-1xm32e0

scheduler:
  parse-offers:
    java:
      mid:
        cron: "0 0 7 * * ?"
        timezone: "Europe/Warsaw"
    python:
      mid:
        cron: "0 0 8 * * ?"
        timezone: "Europe/Warsaw"