server:
  port: 8082

spring:
  mongodb:
    embedded:
      version: 4.7.0
  data:
    mongodb:
      host: ${APP_MONGODB_HOST:localhost}
      port: ${APP_MONGODB_PORT:27017}
      database: ${APP_MONGODB_DATABASE:offer}
      username: ${APP_MONGODB_USERNAME:admin}
      password: ${APP_MONGODB_PASSWORD:admin}
      authentication-database: ${APP_MONGODB_AUTH_DB:admin}
  rabbitmq:
    username: ${RABBIT_USERNAME:max_user_rabbit}
    password: ${RABBIT_PASSWORD:max_password_rabbit}
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}

message-broker-custom-config:
  message:
    expiration-time-ms: 600000
    retry-on-fail:
      max-duration-sec: 30
      interval-ms: 1000
  broker:
    retry-on-fail-connection:
      max-attempts: 4
      exponential-backoff-ms: 6000
      jitter-factor: 0

webdriver:
  scheme: ${WEBDRIVER_SCHEME:http}
  host: ${WEBDRIVER_HOST:localhost}
  port: ${WEBDRIVER_PORT:4444}
  path: ${WEBDRIVER_PATH:/wd/hub}

logging:
  level:
    org.openqa.selenium: ERROR

website-to-parse:
  justjoinit:
    domain: https://justjoin.it
    div-to-offer-list: //*[@id="root"]/div[3]/div[1]/div/div[2]/div[1]/div/div
    offer:
      height: 68px
      end-of-offers-message-announcing: 'Subscribe to the job alert:'
    skill:
      class-name: css-1xm32e0

scheduler:
  parse-offers:
    cron: "0 0 6 * * ?"
    timezone: "Europe/Warsaw"
  init-parse-offers:
    cities:
      - warsaw
      - krakow
      - wroclaw
    technologies:
      - java
      - php
    seniority:
      - mid