apiVersion: v1
kind: Pod
metadata:
  name: mongodb-express-pod
  labels:
    db: mongodb-express
spec:
  containers:
    - name: justjoinit-parser-mongo-db-express
      image: mongo-express:latest
      ports:
        - containerPort: 8081
          name: mongo-expr-port
      envFrom:
        - configMapRef:
            name: mongo-express-cm
  initContainers:
    - name: init-mongo-express
      image: busybox
      command: [ 'sh', '-c', 'until nc -z mongo-db-service 27017; do echo waiting for mongo; sleep 2; done;' ]