apiVersion: v1
kind: Pod
metadata:
  name: mongodb-express-pod
  labels:
    db: mongodb-express
spec:
  containers:
    - name: justjoinit-parser-mongo-db-express
      image: mongo-express:latest
      ports:
        - containerPort: 8081
          name: mongo-expr-port
      env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-db-service
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: admin
  initContainers:
    - name: init-mongo-express
      image: busybox
      command: [ 'sh', '-c', 'until nc -z mongo-db-service 27017; do echo waiting for mongo; sleep 2; done;' ]
